name: CI/CD FastAPI

on:
  push:
    branches:
      - develop
      - main

env:
  IMAGE_NAME: "offdopedro/fastapi-app"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Build e Push no Docker
        run: |
          echo "Fazendo build..."

  Deploy_Homologacao:
    needs: Build
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: homologacao
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ env.IMAGE_NAME }}:latest
            docker stop fastapi-homol || true
            docker rm fastapi-homol || true
            docker run -d --name fastapi-homol -p 8080:8000 ${{ env.IMAGE_NAME }}:latest

  Deploy_Producao:
    needs: Build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: producao
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ env.IMAGE_NAME }}:latest
            docker stop fastapi-prod || true
            docker rm fastapi-prod || true
            docker run -d --name fastapi-prod -p 80:8000 ${{ env.IMAGE_NAME }}:latest
